version: "3"
services:
  nest:
    container_name: nest-app
    restart: always
    build: ./mail-app
    environment: 
      - env_var_name="ddgsgsgs" # here it is
    ports:
      - "3000:3000"
    links:
      - mongo
    command:  npm start
  mongo:
    container_name: mongo-cont
    image: mongo
    restart: always
    ports:
      - "27017:27017"
